### ISSUE TITLE
Can't scan for temporary files in the Maintenance-Module

### ISSUE THREAD

**Issue by hloens** [jweiland-net/bynder2#16]
If I go to the Maintenance-Module and click „Scan temporary files“, I get an error and in the Log you can find the following error message: 
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function JWeiland\Bynder2\Configuration\ExtConf::__construct(), 0 passed in /some/path/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3492 and exactly 1 expected | ArgumentCountError thrown in file /some/path/public/typo3conf/ext/bynder2/Classes/Configuration/ExtConf.php in line 33. Requested URL: https://www.domain.de/typo3/install.php?install[controller]=maintenance&install[context]=backend&install[action]=clearTypo3tempFilesStats
`

**Comment by froemken** [comment]
Hi @hloens 

interesting, as ExtConf is already configured as "public" here: https://github.com/jweiland-net/bynder2/blob/main/Configuration/Services.yaml#L11

Thank you for your help. Needs further investigations. Don't know why DI does not work in Maintenance Module.
@sfroemkenjw 

Stefan
